#pragma once
//放一些全局的头文件和宏定义
#include<iostream>
#include<string>
#include<vector>
#include<list>
#include<unordered_map>
#include<memory>
#include<functional>
#include<mutex>
#include<sstream>
#include<unordered_map>
#include<cstdlib>
#include<stdarg.h>
#include<unistd.h>
#include<chrono>
#include<list>
#include<map>
#include<set>
#include<sys/stat.h>
#include<cstring>
#include<fstream>
#include<yaml-cpp/yaml.h>
#include<boost/lexical_cast.hpp>
#include<boost/type_index.hpp>
#include<cxxabi.h>
#include<unordered_set>
#include<dirent.h>